services:
  player0:
    image: comm-security
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: player0
    #entrypoint: /bin/bash
    ports:
      - "3000:3000"
      - "8000:8000"
    volumes:
      - .:/workspace:cached
    command: sleep infinity

  chain0:
    image: comm-security
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: chain0
    #entrypoint: /bin/bash
    ports:
      - "3001:3001"
    volumes:
      - .:/workspace:cached
    command: sleep infinity
